### ISSUE TITLE
Why you use CPU but not GPU?

### ISSUE THREAD

**Issue by Arsmart123** [asrivast28/ParsiMoNe#1]
Hi! I am reading your paper and find it quite interesting! But I am wondering why you use CPU but not GPU? Also...you are using one CPU with multiple cores, and these cores communicate with MPI, right?

Thank you!!!!

**Comment by asrivast28** [comment]
Hello! Thanks for your interest in the paper!

Our decision to use CPUs for this paper was driven by the availability of the resources to us. Since we had access to a cluster with multiple CPUs, we decided to go with an implementation that used CPUs. I think that the algorithm can be implemented using GPUs as well.

Also, we use multiple CPUs (up to 171) and multiple cores within each CPU (up to 24), and all of these cores communicate using MPI. The algorithm can be implemented using a hybrid shared-distributed memory model, where the cores on the same CPU communicate using OpenMP or something similar. However, we did not do that for the purpose of the SC21 paper.

Hope that helps. Please let me know if you have any other questions.

**Comment by Arsmart123** [comment]
> Hello! Thanks for your interest in the paper!
> 
> Our decision to use CPUs for this paper was driven by the availability of the resources to us. Since we had access to a cluster with multiple CPUs, we decided to go with an implementation that used CPUs. I think that the algorithm can be implemented using GPUs as well.
> 
> Also, we use multiple CPUs (up to 171) and multiple cores within each CPU (up to 24), and all of these cores communicate using MPI. The algorithm can be implemented using a hybrid shared-distributed memory model, where the cores on the same CPU communicate using OpenMP or something similar. However, we did not do that for the purpose of the SC21 paper.
> 
> Hope that helps. Please let me know if you have any other questions.

That helps! Thank you!!!
